### ISSUE TITLE
请问后续增加对文件夹的支持吗？

### ISSUE THREAD

**Issue by HildaM** [siyuan-note/dejavu#7]
如果往siyuan中直接拖入文件夹的话，似乎只能保存快捷连接。这里看到是因为 dejavu 不支持文件夹的同步。这里后续有改进的需求吗？
我也想请教一下：为什么不支持文件夹的同步呢？原因是什么？

**Comment by 88250** [comment]
你好，不会不支持空文件夹同步，谢谢。
